### ISSUE TITLE
running the client server

### ISSUE THREAD

**Issue by a-sanjana** [cake-lab/LitAR#4]
Hi, thank you for sharing your amazing work!

I see that the readme in the client app talks about setting up an endpoint? The folder containing the relevant file for that is not available.

What steps can be followed to run the client app in this case? Thank you!

**Comment by YiqinZhao** [comment]
Hi! Thanks for pointing out this issue. Please find the server-side code in this folder:
https://github.com/cake-lab/LitAR/tree/main/service

**Comment by a-sanjana** [comment]
Thank you so much!
